### ISSUE TITLE
please update imgui to the latest version, thx!

### ISSUE THREAD

**Issue by brucelevis** [c0i/imguix#16]

**Comment by Subtixx** [comment]
I have forked the repository and updated it to 1.63 WIP:
https://github.com/Subtixx/imguix

**Comment by yinjimmy** [comment]
@Subtixx  one PR is welcome.

**Comment by Subtixx** [comment]
Yea I'm still in the middle of testing it though. Haven't tested the LUA stuff

**Comment by yinjimmy** [comment]
Lets update ImGUI to https://github.com/ocornut/imgui/releases/tag/v1.66b .

**Comment by yinjimmy** [comment]
Thanks  https://github.com/Subtixx/imguix/commit/a811934128c3a5b6d4b49660463acb083a6f322b
