### ISSUE TITLE
Sample LUA Window causes mismatch Begin/End

### ISSUE THREAD

**Issue by Subtixx** [c0i/imguix#17]
https://github.com/c0i/imguix/blob/c151b0794a18ebf0b1d764f61053280b93f6a609/Resources/res/main.lua#L64-L66

When the "Toolbar" window is being collapsed it causes ImGui to assert because of mismatched Begin/End. To fix it: "Move imgui.endToLua() outside of the if block."

**Comment by yinjimmy** [comment]
Thanks for your feedback.
