### ISSUE TITLE
Adding ImGUILayer produces OpenGL error 0x0502

### ISSUE THREAD

**Issue by askamn** [c0i/imguix#19]
Hello,

As soon as the ImGUI Layer is added via: 
`addChild(ImGuiLayer::create(), INT_MAX, "ImGUILayer");`

OpenGL errors start throwing up like crazy. 
`OpenGL error 0x0502 in cocos2d/cocos/renderer/CCRenderer.cpp restoreRenderState 189`

The errors are gone if the lines glUseProgram(0); and glUseProgram(1); are commented out in CCImGUILayer.cpp but that ofcourse, also stops the rendering of ImGui elements. So I assume there is something wrong with the program being linked. 

The ImGUI window shows up completely fine, but everything else in the scene is not rendered at all (any sprite, or any node). If I remove the Imgui layer, everything else starts rendering again.

Any help is appreciated. I tried fixing it, but I was unable to. I will try again.

**Cocos Version: 3.17**

**Comment by yinjimmy** [comment]
on mac or win platform?

**Comment by yinjimmy** [comment]
I have updated imguix with cocos2d-x cpp 3.17 version, plz check it.

**Comment by askamn** [comment]
Hello, 

Sorry for the late reply. I had already fixed it in my version but forgot to post here. I have even managed to get Imgui Docking  (the docking branch) working with cocos2dx

**Comment by yinjimmy** [comment]
would you like to share the ImGui Docking code?
