### ISSUE TITLE
Getting Error : OpenGL error 0x0501 in ..\renderer\CCRenderer.cpp cocos2d::RenderQueue::restoreRenderState 192 

### ISSUE THREAD

**Issue by meiry** [c0i/imguix#2]
Using this example code with Cocos2d-x 3.9 in VS 2013 windows 7 64bit 
the window with the "HelloWorld.png" is shown BUT no imgui widegts shown 
im keep getting this error ;
```
OpenGL error 0x0501 in ..\renderer\CCRenderer.cpp cocos2d::RenderQueue::restoreRenderState 192
```

**Comment by yinjimmy** [comment]
Um, i'm fixing it.

**Comment by meiry** [comment]
What is the problem there can you share ?

**Comment by meiry** [comment]
Any news with this ?

**Comment by yinjimmy** [comment]
![image](https://cloud.githubusercontent.com/assets/5056328/11398441/a5b30782-93bb-11e5-91ab-c90b30250c90.png)

**Comment by meiry** [comment]
Nice! 
Does the source code updated ?

**Comment by yinjimmy** [comment]
https://github.com/c0i/imguix/tree/win32

It breaks OS X. Merge into master later..

**Comment by yinjimmy** [comment]
merge back to master branch.
