### ISSUE TITLE
Add android and change something.

### ISSUE THREAD

**Issue by namkazt** [c0i/imguix#9]
hey @yinjimmy 

there is few things here:
1, i was complete android version of imgui ( tested on some devices - not support multi touch yet)
2, i think we don't need to override GlViewImpl there is some other way to implement imgui.
3, CCIMGUI not work right when change scene ( fixed )

please open pull requests.

p/s: i have so busy on there month so i can't finish shadow system yet! but as soon as possible when my job done. ( btw port imgui work on android is a part of my job so i shared it here )

**Comment by yinjimmy** [comment]
> please open pull requests.

??
